nit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -135,7 +135,7 @@ jobs:
         run: |
           echo "Removing yarn.lock due to yarn v1 package resolution issues"
           echo "https://github.com/iarna/wide-align/issues/63"
-          rm yarn.lock
+          rm yarn.lock 2>/dev/null || true  # silent fail if yarn.lock doesn't exist
           yarn && yarn build_test
 
       - name: Check for missing migrations
